const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const DISCORD='https://discord.gg/efdQJsceKb';
const pages=[['home','Home','/'],['matches','Matches','/matches/'],['standings','Standings','/standings/'],['teams','Teams','/teams/'],['players','Players','/players/'],['stats','Stats','/stats/'],['history','History','/history/'],['league','League','/league/'],['news','News','/news/']];
const esc=v=>String(v??'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const brand=()=>`<img class="brand-logo" src="/assets/branding/ssl-logo.svg" alt=""><span class="brand-wordmark"><b><span class="orange">S</span>UPERSONIC <span class="orange">S</span>HOWDOWN</b><strong><span class="orange">L</span>EAGUE <span class="orange">2</span><span class="blue">v</span><span class="orange">2</span></strong></span>`;
function shell(){const current=document.body.dataset.page||'home';document.body.insertAdjacentHTML('afterbegin',`<a class="skip-link" href="#main">Skip to content</a><div class="statusbar"><div class="wrap statusbar-in"><div class="left"><span class="brand-status">Supersonic Showdown League 2v2</span><span class="hide-mobile">Saturday match night · US-East</span></div><span class="mono">showdown2v2.live</span></div></div><header class="site-header"><div class="wrap nav"><a class="brand brand-lockup" href="/" aria-label="Supersonic Showdown League 2v2 home">${brand()}</a><button class="mobile-toggle" aria-label="Open navigation" aria-expanded="false">☰</button><nav class="navlinks" aria-label="Primary navigation">${pages.map(([id,label,url])=>`<a href="${url}"${id===current?' aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="nav-actions"><a class="btn primary" href="${DISCORD}" target="_blank" rel="noopener noreferrer">Join Discord</a></div></div></header>`);document.body.insertAdjacentHTML('beforeend',`<footer class="site-footer"><div class="wrap footer-grid"><div><a class="brand brand-lockup" href="/" aria-label="Supersonic Showdown League 2v2 home">${brand()}</a><p class="legal">Independent community competition. Not affiliated with, endorsed by, or sponsored by Psyonix or Epic Games.</p><p class="footer-meta">© 2026 Supersonic Showdown League 2v2</p></div><nav class="footer-nav" aria-label="Footer navigation">${pages.slice(1).map(([,label,url])=>`<a href="${url}">${label}</a>`).join('')}</nav></div></footer>`);}
function nav(){const b=$('.mobile-toggle'),n=$('.navlinks');if(!b||!n)return;const close=()=>{n.classList.remove('open');b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Open navigation')};b.addEventListener('click',()=>{const open=n.classList.toggle('open');b.setAttribute('aria-expanded',String(open));b.setAttribute('aria-label',open?'Close navigation':'Open navigation')});n.addEventListener('click',e=>{if(e.target.matches('a'))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});}
function tabs(){const buttons=$$('.tab[data-tier]');buttons.forEach(b=>{b.setAttribute('role','tab');b.setAttribute('aria-selected',String(b.classList.contains('active')));b.addEventListener('click',()=>{buttons.forEach(x=>{x.classList.remove('active');x.setAttribute('aria-selected','false')});b.classList.add('active');b.setAttribute('aria-selected','true');renderStandings(b.dataset.tier)})});}
let league={};
function renderStandings(tier='mythic'){const body=$('#standings-body');if(!body)return;const rows=league.standings?.[tier]||[];if(!rows.length){body.innerHTML='<tr class="empty-row"><td colspan="9">Standings will appear here when the table is posted.</td></tr>';return}body.innerHTML=rows.map((r,i)=>`<tr><td class="rank">${esc(r.rank??i+1)}</td><td><strong>${esc(r.team)}</strong></td><td>${esc(r.wins)}</td><td>${esc(r.losses)}</td><td>${esc(r.win_pct)}</td><td>${esc(r.goals_for)}</td><td>${esc(r.goals_against)}</td><td>${esc(r.differential)}</td><td>${esc(r.streak||'—')}</td></tr>`).join('')}
function renderMatches(){const box=$('#match-list');if(!box)return;const rows=[...(league.match_night?.matches||[])].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,12);if(!rows.length){box.innerHTML=`<div class="data-state"><strong>No match slate is posted right now.</strong><br>Check Discord for current scheduling and match-night coordination.</div>`;return}box.innerHTML=rows.map(m=>`<div class="match-row"><span class="tierlabel">${esc(m.tier)}</span><span class="tname">${esc(m.home)}</span><span class="scorebox">${esc(m.score||'VS')}</span><span class="tname away">${esc(m.away)}</span><span class="state">${esc(m.status)}</span></div>`).join('')}
function renderTeams(){const grid=$('#team-grid');if(!grid)return;const rows=league.teams||[];grid.innerHTML=rows.length?rows.map(t=>`<article class="card team-card" data-filterable style="--team-color:${esc(t.color||'#32C8FF')}"><div class="team-logo">${esc(t.franchise_tag||'SSL')}</div><span class="eyebrow">${esc(t.tier)}</span><h3>${esc(t.name)}</h3><div class="team-meta">${esc(t.franchise)}</div></article>`).join(''):'<div class="data-state" style="grid-column:1/-1"><strong>Team directory is coming soon.</strong></div>'}
function renderPlayers(){const grid=$('#player-grid');if(!grid)return;const rows=league.players||[];grid.innerHTML=rows.length?rows.map(p=>`<article class="card player-tile" data-filterable><span class="eyebrow">${esc(p.tier)}</span><h3>${esc(p.gamertag)}</h3><div class="player-meta">${esc(p.team)} · ${esc(p.role||'Player')}</div></article>`).join(''):`<div class="data-state" style="grid-column:1/-1"><strong>Player cards are coming soon.</strong><br>Join Discord to register and follow player updates.</div>`}
function renderPower(){const box=$('#power-list');if(!box)return;const rows=league.power_rankings||[];box.innerHTML=rows.length?rows.map((r,i)=>`<div class="leader-row"><span class="pos">${String(i+1).padStart(2,'0')}</span><div><b>${esc(r.team)}</b><span>${esc(r.note||'')}</span></div><div class="value">${esc(r.score)}</div></div>`).join(''):'<div class="data-state"><strong>Power rankings are coming soon.</strong><br>Follow the standings for the current division order.</div>'}
function renderHistory(){const box=$('#champion-list');if(!box)return;const rows=league.champions||[];box.innerHTML=rows.length?rows.map(c=>`<article class="card record-card"><span>${esc(c.season)}</span><b>${esc(c.team)}</b><div class="muted">${esc(c.tier||'League champion')}</div></article>`).join(''):'<div class="data-state" style="grid-column:1/-1"><strong>League history is coming soon.</strong><br>Champions, records, and season stories will live here.</div>'}
function renderNews(){const box=$('#news-grid'),rows=league.news||[];if(!box||!rows.length)return;box.innerHTML=rows.slice(0,9).map((n,i)=>`<article class="card news-card${i===0?' feature':''}"><span class="eyebrow">${esc(n.category||'League news')}</span><h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p><time>${esc(n.date)}</time></article>`).join('')}
function filter(){const input=$('[data-filter]');if(!input)return;input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();$$('[data-filterable]').forEach(card=>card.hidden=!!q&&!card.textContent.toLowerCase().includes(q))})}
async function start(){shell();nav();tabs();filter();try{const r=await fetch('/data/league.json',{cache:'no-store'});if(!r.ok)throw new Error();league=await r.json()}catch{league={}}renderMatches();renderStandings($('.tab.active[data-tier]')?.dataset.tier||'mythic');renderTeams();renderPlayers();renderPower();renderHistory();renderNews();}
start();
