const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const DEFAULT_DISCORD='https://discord.gg/efdQJsceKb';
let league=null;
function setNav(){const toggle=$('.mobile-toggle'),nav=$('.navlinks');if(toggle&&nav)toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});}
function brandLockup(){return '<span class="brand-mark" aria-hidden="true"><span>SS</span></span><span class="brand-copy"><b><span class="orange">S</span>UPERSONIC <span class="orange">S</span>HOWDOWN</b><strong><span class="orange">L</span>EAGUE <span class="orange">2</span><span class="blue">v</span><span class="orange">2</span></strong></span>';}
function applyBranding(){
  $$('.brand').forEach(a=>{a.classList.add('brand-lockup');a.setAttribute('aria-label','Supersonic Showdown League 2v2 home');a.innerHTML=brandLockup();});
  document.querySelector('meta[name="theme-color"]')?.setAttribute('content','#07101D');
}
function activateDiscord(){const invite=league?.community?.discord_invite||DEFAULT_DISCORD;$$('a').forEach(a=>{const txt=(a.textContent||'').toLowerCase();if(txt.includes('discord')&&(txt.includes('pending')||txt.includes('invite')||txt.includes('join'))){a.href=invite;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Join Discord';a.classList.remove('disabled');}});$$('.chip.pending').forEach(x=>x.remove());}
function seasonLabels(){const name=league?.season?.name;const week=league?.season?.week;$$('[data-season]').forEach(x=>{if(name)x.textContent=name;else x.closest('.chip')?.remove();});$$('[data-week]').forEach(x=>{if(week)x.textContent=`Week ${week}`;else x.closest('.chip')?.remove();});$$('[data-generated]').forEach(x=>x.textContent=league?.generated_at?new Date(league.generated_at).toLocaleString():'Public competition snapshot not yet published');}
function renderStandings(tier){const body=$('#standings-body');if(!body)return;const rows=league?.standings?.[tier]||[];const labels={mythic:'MYTHIC',legend:'LEGEND',elite:'ELITE',contender:'CONTENDER',rookie:'ROOKIE',amateur:'AMATEUR'};if(!rows.length){body.innerHTML=`<tr class="empty-row"><td colspan="9"><strong>${labels[tier]||esc(tier)}</strong> standings have not yet been published to the public web snapshot.</td></tr>`;return;}body.innerHTML=rows.map((r,i)=>`<tr><td class="rank">${esc(r.rank??i+1)}</td><td><strong>${esc(r.team)}</strong></td><td>${esc(r.wins)}</td><td>${esc(r.losses)}</td><td>${esc(r.win_pct)}</td><td>${esc(r.goals_for)}</td><td>${esc(r.goals_against)}</td><td>${esc(r.differential)}</td><td>${esc(r.streak)}</td></tr>`).join('');}
function standingsTabs(){$$('.tab[data-tier]').forEach(btn=>btn.addEventListener('click',()=>{$$('.tab[data-tier]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderStandings(btn.dataset.tier);}));renderStandings($('.tab.active[data-tier]')?.dataset.tier||'mythic');}
function renderMatches(){const list=$('#match-list');if(!list)return;const rows=league?.match_night?.matches||[];if(!rows.length){list.innerHTML='<div class="data-state"><strong>No public match slate is posted right now.</strong> Verified fixtures and results will appear here automatically when published by the league data feed.</div>';return;}list.innerHTML=rows.slice(0,12).map(m=>`<div class="match-row"><span class="tierlabel">${esc(m.tier)}</span><span class="tname">${esc(m.home)}</span><span class="scorebox">${esc(m.score??'VS')}</span><span class="tname away">${esc(m.away)}</span><span class="state">${esc(m.status)}</span></div>`).join('');}
function renderTeams(){const grid=$('#team-grid');if(!grid)return;const teams=league?.teams||[];if(!teams.length){grid.innerHTML='<div class="data-state" style="grid-column:1/-1"><strong>No active-team identity snapshot is published on the web yet.</strong></div>';return;}grid.innerHTML=teams.map(t=>{const stats=[t.wins,t.losses,t.streak].some(v=>v!==undefined&&v!==null);return `<article class="card team-card" data-filterable style="--team-color:${esc(t.color||'#49C7FF')}"><div class="team-logo">${t.logo?`<img src="${esc(t.logo)}" alt="${esc(t.franchise||t.name)} logo">`:esc(t.franchise_tag||'SSL')}</div><span class="eyebrow">${esc(t.tier)} · ${esc(t.franchise_tag||'SSL')}</span><h3>${esc(t.name)}</h3><div class="team-meta">${esc(t.franchise||'Supersonic Showdown')}</div>${stats?`<div class="statline"><div><b>${esc(t.wins)}</b><span>Wins</span></div><div><b>${esc(t.losses)}</b><span>Losses</span></div><div><b>${esc(t.streak)}</b><span>Streak</span></div></div>`:''}</article>`;}).join('');}
function renderPlayers(){const grid=$('#player-grid');if(!grid)return;const players=league?.players||[];if(!players.length){grid.innerHTML='<div class="data-state" style="grid-column:1/-1"><strong>No public player snapshot is published on the web yet.</strong> Player cards will populate only from approved league statistics.</div>';return;}grid.innerHTML=players.map(p=>`<article class="card player-tile" data-filterable><span class="eyebrow">${esc(p.tier)}</span><h3>${esc(p.gamertag)}</h3><div class="player-meta">${esc(p.team)} · ${esc(p.role||'Player')}</div><div class="statline"><div><b>${esc(p.record)}</b><span>Record</span></div><div><b>${esc(p.goals)}</b><span>Goals</span></div><div><b>${esc(p.mvps)}</b><span>MVPs</span></div></div></article>`).join('');}
function renderRankings(){const box=$('#power-list');if(!box)return;const rows=league?.power_rankings||[];if(!rows.length){box.innerHTML='<div class="data-state"><strong>No official Power Index is published on the website right now.</strong> Official standings remain the competitive authority.</div>';return;}box.innerHTML=rows.map((r,i)=>`<div class="leader-row"><span class="pos">${String(i+1).padStart(2,'0')}</span><div><b>${esc(r.team)}</b><span>${esc(r.note)}</span></div><div class="value">${esc(r.score)}</div></div>`).join('');}
function renderChampions(){const box=$('#champion-list');if(!box)return;const rows=league?.champions||[];if(!rows.length){box.innerHTML='<div class="data-state"><strong>The verified historical archive has not yet been published to the website.</strong> Champion records will appear only from reconciled league history.</div>';return;}box.innerHTML=rows.map(c=>`<article class="card record-card"><span>${esc(c.season)}</span><b>${esc(c.team)}</b><div class="muted">${esc(c.tier||'League champion')}</div></article>`).join('');}
function renderNews(){const box=$('#news-grid');if(!box)return;const rows=league?.news||[];if(!rows.length)return;box.innerHTML=rows.slice(0,9).map((n,i)=>`<article class="card news-card${i===0?' feature':''}"><span class="eyebrow">${esc(n.category||'League desk')}</span><h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p><time>${esc(n.date)}</time></article>`).join('');}
function cleanStaticPlaceholders(){$$('.leader-row b,.record-card b,.data-state strong').forEach(el=>{const t=el.textContent.toLowerCase();if(t.includes('pending')||t.includes('awaiting'))el.closest('.leader-row,.record-card')?.remove();});$$('p,time,span').forEach(el=>{const t=el.textContent.trim().toLowerCase();if(t==='integration queue'||t==='input needed'||t.includes('feed pending'))el.remove();});}
function filterCards(){const input=$('[data-filter]');if(!input)return;input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();$$('[data-filterable]').forEach(card=>card.hidden=q&&!card.textContent.toLowerCase().includes(q));});}
async function load(){applyBranding();try{const r=await fetch('/data/league.json',{cache:'no-store'});if(!r.ok)throw new Error(r.status);league=await r.json();document.documentElement.dataset.feed='ready';}catch(e){league=null;document.documentElement.dataset.feed='offline';}activateDiscord();seasonLabels();standingsTabs();renderMatches();renderTeams();renderPlayers();renderRankings();renderChampions();renderNews();cleanStaticPlaceholders();}
setNav();applyBranding();activateDiscord();filterCards();load();
