(()=>{'use strict';
const C='supersonicshowdownleague',P=location.hostname||'showdown2v2.live',M='/data/media.json',q=s=>document.querySelector(s),safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let player,media={videos:[],highlights:[]},filter='all';
const push=(e,d={})=>{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:e,page_path:location.pathname,twitch_channel:C,...d});};
function status(t,live=false){const s=q('#twitch-status'),d=q('#twitch-live-dot');if(s)s.textContent=t;if(d)d.classList.toggle('live',live);}
function create(){if(!window.Twitch?.Player||player)return;player=new Twitch.Player('twitch-player',{channel:C,parent:[P],width:'100%',height:'100%',autoplay:true,muted:true});player.addEventListener(Twitch.Player.READY,()=>{status('Official SSL channel · autoplaying muted');try{player.setMuted(true);player.play()}catch{}push('twitch_embed_ready')});player.addEventListener(Twitch.Player.ONLINE,()=>{status('LIVE NOW · official SSL broadcast',true);try{player.setMuted(true);player.play()}catch{}push('twitch_stream_online')});player.addEventListener(Twitch.Player.OFFLINE,()=>status('Currently offline · next official stream Saturday 9:30 PM ET'));player.addEventListener(Twitch.Player.PLAYING,()=>push('twitch_embed_play'));}
function load(){if(!q('#twitch-player'))return;if(window.Twitch?.Player)return create();const e=q('script[src="https://player.twitch.tv/js/embed/v1.js"]');if(e){e.addEventListener('load',create,{once:true});return}const s=document.createElement('script');s.src='https://player.twitch.tv/js/embed/v1.js';s.async=true;s.onload=create;s.onerror=()=>status('Twitch player unavailable · open the channel directly');document.head.append(s);}
function play(v,o=0){if(!player){open(v.url,'_blank','noopener,noreferrer');return}try{player.setVideo(String(v.id),Number(o)||0);player.setMuted(false);player.play();q('#twitch-player-shell')?.scrollIntoView({behavior:'smooth',block:'center'});status(`Playing: ${v.title}`);push('media_play_in_embed',{media_id:v.id,title:v.title})}catch{open(v.url,'_blank','noopener,noreferrer')}}
function date(v){const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
function card(v,kind){const hi=kind==='highlight',id=hi?v.video_id:v.id,o=hi?v.vod_offset_seconds:0;return `<article class="card media-card"><a class="media-thumb" href="${safe(v.url)}" target="_blank" rel="noopener noreferrer"><img src="${safe(v.thumbnail)}" alt="" loading="lazy" decoding="async"><span class="media-badge">${hi?'Highlight':'Broadcast'}</span><span class="media-duration">${safe(v.duration)}</span></a><div class="media-card-body"><span class="eyebrow">${safe(date(v.published_at))}</span><h3>${safe(v.title)}</h3><p>${safe(v.view_count)} Twitch views${hi&&v.featured?' · Featured':''}</p><div class="media-card-actions">${id?`<button type="button" data-play="${safe(id)}" data-offset="${safe(o)}" data-title="${safe(v.title)}" data-url="${safe(v.url)}">Play here</button>`:''}<a href="${safe(v.url)}" target="_blank" rel="noopener noreferrer">Open on Twitch →</a></div></div></article>`}
function render(){const b=q('#broadcast-grid'),h=q('#highlight-grid'),bs=q('#broadcasts'),hs=q('#highlights');if(bs)bs.hidden=filter==='highlight';if(hs)hs.hidden=filter==='broadcast';if(b)b.innerHTML=media.videos?.length?media.videos.map(v=>card(v,'broadcast')).join(''):'<div class="media-empty">No archived broadcasts are published yet.</div>';if(h)h.innerHTML=media.highlights?.length?media.highlights.map(v=>card(v,'highlight')).join(''):'<div class="media-empty">No curated highlights are published yet.</div>';}
async function library(){try{const r=await fetch(M,{cache:'no-store'});if(!r.ok)throw 0;media=await r.json();render();const u=q('#media-updated');if(u)u.textContent=`Curated ${date(media.updated_at)}`}catch{['#broadcast-grid','#highlight-grid'].forEach(s=>{const x=q(s);if(x)x.innerHTML='<div class="media-empty">Media catalog temporarily unavailable. Open Twitch for the latest videos.</div>'})}}
document.addEventListener('click',e=>{const f=e.target.closest('[data-media-filter]');if(f){filter=f.dataset.mediaFilter||'all';document.querySelectorAll('[data-media-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===f)));render();return}const b=e.target.closest('[data-play]');if(b)play({id:b.dataset.play,title:b.dataset.title,url:b.dataset.url},b.dataset.offset)});
push('view_twitch_hub',{destination:'embedded_player'});load();library();})();
